# Configuration options are documented at:
# http://about.travis-ci.org/docs/user/languages/ruby/
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.1
gemfile:
  - test/Gemfile
script: cd test; bundle exec rake
