# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'sass',       "~> 3.4"

group :test do
  gem 'compass',  "~> 1.0"
  gem 'rake'
  gem "diffy",    "~> 3.0.1"
  gem "colorize", "~> 0.6.0"
  gem 'minitest', "~> 5.6"
end
